### ISSUE TITLE
Player entitiy (currently called Spaceship) should have a ManualBlasterComponent for firing blasts

### ISSUE THREAD

**Issue by cdsupina** [amethyst/space_shooter_rs#49]
The ManualBlasterComponent would be used for spawning blasts when input is pressed.

**Comment by tigleym** [comment]
I think we can reuse the [logic for spawning (firing) blasts](https://github.com/amethyst/space_shooter_rs/blob/cdsupina-dev/src/systems/autoblaster_system.rs#L73-L169) from `fire_when_ready` in the autoblaster_system file to help with this. Perhaps we can make the `AutoBlasterComponent` generic so that it can also be attached to the player entity and when input is handled by the spaceship system, the component can call a method that spawns the blasts:

It could look something like this:

1. Rename `AutoBlasterComponent` --> `BlasterComponent`. 

The `BlastComponent` would have all the same properties minus `fire_period` and `fire_timer`. `fire_period` and `fire_timer` would instead be contained by another component called `AutoFireComponent` and this is what would be used to automate firing blasts in the autoblaster system. 

2. Implement a method on `BlasterComponent` that contains the logic for creating data to pass to `spawn_blasts`: (https://github.com/amethyst/space_shooter_rs/blob/cdsupina-dev/src/systems/autoblaster_system.rs#L73-L169). Perhaps it can be called `fire()?`

```rust
impl BlasterComponent {
  pub fn fire() {
       .....
       spawn_blasts(...)
  }
}
```

The problem with this is that we wanted to keep logic out of components as much as we can. But perhaps we can make an exception for this to avoid duplicating logic for enemy and player entities.

3. By renaming to `BlasterComponent` and creating an `AutoFireComponent`, we can still have the concept of an entity being an "auto blaster" by attaching both these components to it. Any other entity with just the `BlasterComponent` will need to manually call `Blaster.fire()` when input is received. Because of this, I propose these small modifications to the following systems:

- **systems/autoblaster_system.rs**:

```rust
fn fire_when_ready(
    blaster: &mut BlasterComponent,
    auto_fire: &AutoFireComponent, // automates firing
    source_motion2d: &Motion2DComponent,
    source_transform: &Transform,
    delta_time: f32,
    entities: &Entities,
    sprite_resource: &ReadExpect<SpriteResource>,
    lazy_update: &ReadExpect<LazyUpdate>,
) {
    if auto_fire.timer > 0.0 {
        auto_fire.timer -= delta_time;
    } else {
        auto_fire.timer = auto_fire.period;
        blaster_component.fire(source_motion2d, source_transform, delta_time, entities, sprite_resource, lazy_update);
    }
}
```

- In **systems/spaceship.rs**:

```rust 
// after detecting the `shoot_action`
blaster_component.fire(...)
```

@cdsupina let me know what you think about this!

**Comment by cdsupina** [comment]
I think this is a very thoughtful solution and makes a lot of sense. I will reference this comment when working on this issue.

**Comment by cdsupina** [comment]
While implementing this I have one small change to suggest. I think we also should add a ManualFireComponent. This component is needed because there still needs to be a cooldown on the Player's blaster. For now, the ManualFireComponent would have the same properties as the AutoFireComponent:

```rust
pub struct ManualFireComponent {
    pub period: f32,
    pub timer: f32,
}
```

But in the future, when we refactor the Player's logic, we may need to add more properties to this component. For example, currently, when the player is executing a barrel roll action they cannot fire the blasters. It may make sense to add properties to
to the ManualFireComponent that stores data on whether the player's firing is inhibited in some way.

**Comment by tigleym** [comment]
> I think we also should add a ManualFireComponent. This component is needed because there still needs to be a cooldown on the Player's blaster. 

I missed that the `Spaceship` component still had `fire_cooldown` implemented on it from the `Fires` trait in my initial comment. Could I suggest an alternative? 

**Attach to both the Spaceship and Enemy entities:**
```rust
/// Data for describing characteristics about the attached entity's 
/// spawned blast components.
pub struct BlasterComponent {
    pub count: usize,
    pub allied: bool,
    pub shot_velocity: Vector2<f32>,
    pub velocity_multiplier: f32,
    pub offset: Vector2<f32>,
    pub damage: f32,
    pub poison_damage: f32, 
    pub poison_chance: f32,
    pub crit_chance: f32,
    pub size_multiplier: f32,
    pub spacing: f32,
}

/// The firing cycle of the entity's blasts. 
/// Helps control the frequency of blasts an entity with a BlasterComponent can fire. 
struct FireCycle {
    pub period: f32,
    pub timer: f32,
}
```
^ The above would then result in this refactor to only a `BlasterComponent` and `FireCycle` component. We can then avoid creating another component that's specific to the player. However, one caveat to doing this is that the `autoblaster_system` would need to be tweaked to only entities that are not "players". I don't think would be too much of a change. 

I wanted to avoid having components with properties that served the same purposes. By having `ManualFireComponent` and `AutoFireComponent` both have the same structure (currently), it seems like we are duplicating functionalities here.

**Comment by tigleym** [comment]
In #56, having a separate manual blaster component is necessary here. See @cdsupina's comment: https://github.com/amethyst/space_shooter_rs/pull/56/files/f8d95809d073f959c1694717b20c35430d750fe9#diff-b0cd261325b653caa1ffe021a62b8233
